/*

 AQUARIUM_TS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __aquarium_ts_h_INCLUDE
#define __aquarium_ts_h_INCLUDE

/* Bank of tiles. */
#define aquarium_tsBank 0

/* Super Gameboy palette 0 */
#define aquarium_tsSGBPal0c0 6076
#define aquarium_tsSGBPal0c1 8935
#define aquarium_tsSGBPal0c2 6596
#define aquarium_tsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define aquarium_tsSGBPal1c0 6076
#define aquarium_tsSGBPal1c1 8935
#define aquarium_tsSGBPal1c2 6596
#define aquarium_tsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define aquarium_tsSGBPal2c0 6076
#define aquarium_tsSGBPal2c1 8935
#define aquarium_tsSGBPal2c2 6596
#define aquarium_tsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define aquarium_tsSGBPal3c0 6076
#define aquarium_tsSGBPal3c1 8935
#define aquarium_tsSGBPal3c2 6596
#define aquarium_tsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define aquarium_tsCGBPal0c0 27614
#define aquarium_tsCGBPal0c1 32713
#define aquarium_tsCGBPal0c2 32514
#define aquarium_tsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define aquarium_tsCGBPal1c0 9214
#define aquarium_tsCGBPal1c1 3935
#define aquarium_tsCGBPal1c2 330
#define aquarium_tsCGBPal1c3 0

/* Gameboy Color palette 2 */
#define aquarium_tsCGBPal2c0 32713
#define aquarium_tsCGBPal2c1 19481
#define aquarium_tsCGBPal2c2 14355
#define aquarium_tsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define aquarium_tsCGBPal3c0 32713
#define aquarium_tsCGBPal3c1 3935
#define aquarium_tsCGBPal3c2 1294
#define aquarium_tsCGBPal3c3 0

/* Gameboy Color palette 4 */
#define aquarium_tsCGBPal4c0 27614
#define aquarium_tsCGBPal4c1 25545
#define aquarium_tsCGBPal4c2 25348
#define aquarium_tsCGBPal4c3 0

/* Gameboy Color palette 5 */
#define aquarium_tsCGBPal5c0 27614
#define aquarium_tsCGBPal5c1 8935
#define aquarium_tsCGBPal5c2 6596
#define aquarium_tsCGBPal5c3 0

/* Gameboy Color palette 6 */
#define aquarium_tsCGBPal6c0 25545
#define aquarium_tsCGBPal6c1 25545
#define aquarium_tsCGBPal6c2 25348
#define aquarium_tsCGBPal6c3 0

/* Gameboy Color palette 7 */
#define aquarium_tsCGBPal7c0 9959
#define aquarium_tsCGBPal7c1 9959
#define aquarium_tsCGBPal7c2 7620
#define aquarium_tsCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char aquarium_tsCGB[];
/* Start of tile array. */
extern const unsigned char aquarium_ts[];

#endif

/* End of AQUARIUM_TS.H */
