/*

 BUBBLES_TS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __bubbles_ts_h_INCLUDE
#define __bubbles_ts_h_INCLUDE

/* Bank of tiles. */
#define bubbles_tsBank 0

/* Super Gameboy palette 0 */
#define bubbles_tsSGBPal0c0 6076
#define bubbles_tsSGBPal0c1 8935
#define bubbles_tsSGBPal0c2 6596
#define bubbles_tsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bubbles_tsSGBPal1c0 6076
#define bubbles_tsSGBPal1c1 8935
#define bubbles_tsSGBPal1c2 6596
#define bubbles_tsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bubbles_tsSGBPal2c0 6076
#define bubbles_tsSGBPal2c1 8935
#define bubbles_tsSGBPal2c2 6596
#define bubbles_tsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bubbles_tsSGBPal3c0 6076
#define bubbles_tsSGBPal3c1 8935
#define bubbles_tsSGBPal3c2 6596
#define bubbles_tsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bubbles_tsCGBPal0c0 32767
#define bubbles_tsCGBPal0c1 32713
#define bubbles_tsCGBPal0c2 32514
#define bubbles_tsCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define bubbles_tsCGBPal1c0 32767
#define bubbles_tsCGBPal1c1 25545
#define bubbles_tsCGBPal1c2 25346
#define bubbles_tsCGBPal1c3 32767

/* Gameboy Color palette 2 */
#define bubbles_tsCGBPal2c0 32767
#define bubbles_tsCGBPal2c1 8935
#define bubbles_tsCGBPal2c2 6596
#define bubbles_tsCGBPal2c3 32767

/* Gameboy Color palette 3 */
#define bubbles_tsCGBPal3c0 6076
#define bubbles_tsCGBPal3c1 8935
#define bubbles_tsCGBPal3c2 6596
#define bubbles_tsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define bubbles_tsCGBPal4c0 6076
#define bubbles_tsCGBPal4c1 8935
#define bubbles_tsCGBPal4c2 6596
#define bubbles_tsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bubbles_tsCGBPal5c0 6076
#define bubbles_tsCGBPal5c1 8935
#define bubbles_tsCGBPal5c2 6596
#define bubbles_tsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bubbles_tsCGBPal6c0 6076
#define bubbles_tsCGBPal6c1 8935
#define bubbles_tsCGBPal6c2 6596
#define bubbles_tsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bubbles_tsCGBPal7c0 6076
#define bubbles_tsCGBPal7c1 8935
#define bubbles_tsCGBPal7c2 6596
#define bubbles_tsCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char bubbles_tsCGB[];
/* Start of tile array. */
extern const unsigned char bubbles_ts[];

#endif

/* End of BUBBLES_TS.H */
