/*

 MENU_TS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __menu_ts_h_INCLUDE
#define __menu_ts_h_INCLUDE

/* Bank of tiles. */
#define menu_tsBank 0
/* Start of tile array. */
extern const unsigned char menu_ts[];

#endif

/* End of MENU_TS.H */
