/*

 SHOP_CURSOR_TS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __shop_cursor_ts_h_INCLUDE
#define __shop_cursor_ts_h_INCLUDE

/* Bank of tiles. */
#define shop_cursor_tsBank 0

/* Super Gameboy palette 0 */
#define shop_cursor_tsSGBPal0c0 6076
#define shop_cursor_tsSGBPal0c1 8935
#define shop_cursor_tsSGBPal0c2 6596
#define shop_cursor_tsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define shop_cursor_tsSGBPal1c0 6076
#define shop_cursor_tsSGBPal1c1 8935
#define shop_cursor_tsSGBPal1c2 6596
#define shop_cursor_tsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define shop_cursor_tsSGBPal2c0 6076
#define shop_cursor_tsSGBPal2c1 8935
#define shop_cursor_tsSGBPal2c2 6596
#define shop_cursor_tsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shop_cursor_tsSGBPal3c0 6076
#define shop_cursor_tsSGBPal3c1 8935
#define shop_cursor_tsSGBPal3c2 6596
#define shop_cursor_tsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shop_cursor_tsCGBPal0c0 6076
#define shop_cursor_tsCGBPal0c1 8935
#define shop_cursor_tsCGBPal0c2 6596
#define shop_cursor_tsCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shop_cursor_tsCGBPal1c0 6076
#define shop_cursor_tsCGBPal1c1 8935
#define shop_cursor_tsCGBPal1c2 6596
#define shop_cursor_tsCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shop_cursor_tsCGBPal2c0 6076
#define shop_cursor_tsCGBPal2c1 8935
#define shop_cursor_tsCGBPal2c2 6596
#define shop_cursor_tsCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shop_cursor_tsCGBPal3c0 6076
#define shop_cursor_tsCGBPal3c1 8935
#define shop_cursor_tsCGBPal3c2 6596
#define shop_cursor_tsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shop_cursor_tsCGBPal4c0 6076
#define shop_cursor_tsCGBPal4c1 8935
#define shop_cursor_tsCGBPal4c2 6596
#define shop_cursor_tsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shop_cursor_tsCGBPal5c0 6076
#define shop_cursor_tsCGBPal5c1 8935
#define shop_cursor_tsCGBPal5c2 6596
#define shop_cursor_tsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shop_cursor_tsCGBPal6c0 6076
#define shop_cursor_tsCGBPal6c1 8935
#define shop_cursor_tsCGBPal6c2 6596
#define shop_cursor_tsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shop_cursor_tsCGBPal7c0 6076
#define shop_cursor_tsCGBPal7c1 8935
#define shop_cursor_tsCGBPal7c2 6596
#define shop_cursor_tsCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char shop_cursor_tsCGB[];
/* Start of tile array. */
extern const unsigned char shop_cursor_ts[];

#endif

/* End of SHOP_CURSOR_TS.H */
