/*

 SHOP_CURSOR_TS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
const unsigned char shop_cursor_tsCGB[] =
{
  0x00,0x00
};
/* Start of tile array. */
const unsigned char shop_cursor_ts[] =
{
  0x00,0x00,0xC0,0xC0,0xE0,0xE0,0xF0,0xF0,
  0xF0,0xF0,0xE0,0xE0,0xC0,0xC0,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of SHOP_CURSOR_TS.C */
