/*

 TRIGGERFISH_TS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __triggerfish_ts_h_INCLUDE
#define __triggerfish_ts_h_INCLUDE

/* Bank of tiles. */
#define triggerfish_tsBank 0

/* Super Gameboy palette 0 */
#define triggerfish_tsSGBPal0c0 6076
#define triggerfish_tsSGBPal0c1 8935
#define triggerfish_tsSGBPal0c2 6596
#define triggerfish_tsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define triggerfish_tsSGBPal1c0 6076
#define triggerfish_tsSGBPal1c1 8935
#define triggerfish_tsSGBPal1c2 6596
#define triggerfish_tsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define triggerfish_tsSGBPal2c0 6076
#define triggerfish_tsSGBPal2c1 8935
#define triggerfish_tsSGBPal2c2 6596
#define triggerfish_tsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define triggerfish_tsSGBPal3c0 6076
#define triggerfish_tsSGBPal3c1 8935
#define triggerfish_tsSGBPal3c2 6596
#define triggerfish_tsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define triggerfish_tsCGBPal0c0 32767
#define triggerfish_tsCGBPal0c1 32195
#define triggerfish_tsCGBPal0c2 31744
#define triggerfish_tsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define triggerfish_tsCGBPal1c0 6076
#define triggerfish_tsCGBPal1c1 8935
#define triggerfish_tsCGBPal1c2 6596
#define triggerfish_tsCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define triggerfish_tsCGBPal2c0 6076
#define triggerfish_tsCGBPal2c1 8935
#define triggerfish_tsCGBPal2c2 6596
#define triggerfish_tsCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define triggerfish_tsCGBPal3c0 6076
#define triggerfish_tsCGBPal3c1 8935
#define triggerfish_tsCGBPal3c2 6596
#define triggerfish_tsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define triggerfish_tsCGBPal4c0 6076
#define triggerfish_tsCGBPal4c1 8935
#define triggerfish_tsCGBPal4c2 6596
#define triggerfish_tsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define triggerfish_tsCGBPal5c0 6076
#define triggerfish_tsCGBPal5c1 8935
#define triggerfish_tsCGBPal5c2 6596
#define triggerfish_tsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define triggerfish_tsCGBPal6c0 6076
#define triggerfish_tsCGBPal6c1 8935
#define triggerfish_tsCGBPal6c2 6596
#define triggerfish_tsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define triggerfish_tsCGBPal7c0 6076
#define triggerfish_tsCGBPal7c1 8935
#define triggerfish_tsCGBPal7c2 6596
#define triggerfish_tsCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char triggerfish_tsCGB[];
/* Start of tile array. */
extern const unsigned char triggerfish_ts[];

#endif

/* End of TRIGGERFISH_TS.H */
