/*

 AQUARIUM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\manue\Desktop\VirtuaQuario\ROM\TILES\aquarium_ts.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 38
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __aquarium_h_INCLUDE
#define __aquarium_h_INCLUDE

#define aquariumWidth 20
#define aquariumHeight 18
#define aquariumBank 0

#define aquarium aquariumPLN0
extern const unsigned char aquariumPLN0[];
extern const unsigned char aquariumPLN1[];

#endif

/* End of AQUARIUM.H */
