/*

 MENU.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 5
   Tile set      : C:\Users\manue\Desktop\VirtuaQuario\ROM\TILES\menu_ts.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 62
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menuWidth 5
#define menuHeight 5
#define menuBank 0

#define menu menuPLN0
const unsigned char menuPLN0[] =
{
  0x3E,0x3F,0x4E,0x42,0x43,0x40,0x41,0x4E,0x44,0x45,
  0x4E,0x4E,0x4E,0x4E,0x4E,0x46,0x47,0x4E,0x4A,0x4B,
  0x48,0x49,0x4E,0x4C,0x4D
};

/* End of MENU.C */
