/*

 MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 5
   Tile set      : C:\Users\manue\Desktop\VirtuaQuario\ROM\TILES\menu_ts.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 62
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __menu_h_INCLUDE
#define __menu_h_INCLUDE

#define menuWidth 5
#define menuHeight 5
#define menuBank 0

#define menu menuPLN0
extern const unsigned char menuPLN0[];

#endif

/* End of MENU.H */
