/*

 SHOP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\manue\Desktop\VirtuaQuario\ROM\TILES\shop_ts.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 79
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __shop_h_INCLUDE
#define __shop_h_INCLUDE

#define shopWidth 20
#define shopHeight 18
#define shopBank 0

#define shop shopPLN0
extern const unsigned char shopPLN0[];
extern const unsigned char shopPLN1[];

#endif

/* End of SHOP.H */
